### ISSUE TITLE
No command running [BUG]

### ISSUE THREAD

**Issue by LaSecteDuChaton** [Steel-Dev/Monstrorvm#5]
**Describe the bug**
I installed the plugin on my server. I launched with all examples and I tried with wiki to create 2 customs enchants. When reloading, no error appears, but no command is running, it responds like I wrote nothing.

**To Reproduce**
I tried first /monstrorvmreload and then /mvmenchant, /cenchantitem and /applycustommvenchant but nothing happen.

**Expected behavior**
I expected for the first command to reload the plugin and seconds to enchant.

**Screenshots**

**Plugin Version**
monstrorvm1.0.9.jar

**Server Version**
Spigot/Bukkit 1.16.4

**Additional context**
I put on this server to test this plugin for then put it on another server on 1.16.5

**Comment by Steel-Dev** [comment]
Did anything show in console when the plugin was enabling/when executing commands?
I know you said there was no error, but please check console again just in case.

**Comment by Steel-Dev** [comment]
You have an update on this? I can't help unless I know what went wrong exactly. I need a little more information.

**Comment by LaSecteDuChaton** [comment]
I tried again and nothing appears at all in the console, it looks like I
never run a command

**Comment by Steel-Dev** [comment]
Do you have any plugins that might be blocking commands?

**Comment by LaSecteDuChaton** [comment]
I tested the plugin alone to exclude any incompatibility in case of errors

**Comment by Steel-Dev** [comment]
The plugin was developed for 1.16.5, you might need to be using that version.

**Comment by LaSecteDuChaton** [comment]
ok thanks, I checked everything and I was testing on 1.16.4
I'll give you some news about the next testing session :)

**Comment by Steel-Dev** [comment]
How'd it go?

**Comment by LaSecteDuChaton** [comment]
It went well. thanks btw for the help :)

**Comment by Steel-Dev** [comment]
You're welcome.
